name: Quality Check Terraform Code

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - '.gitignore'
  workflow_call:

env:
  TF_IN_AUTOMATION: "1"
  TF_VAR_github_token: ${{ secrets.GH_TOKEN }} # repositories will be created unde the user associated with this PAT

jobs:

  init-validate-plan:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run 'terraform fmt'
        id: fmt
        run: terraform fmt -check -recursive
      
      - name: Run 'terraform init'
        id: init
        run: |
          terraform init -upgrade
       
      - name: Run 'terraform validate'
        id: validate
        run: terraform validate -no-color

      - name: Run 'terraform plan'
        id: planStep
        run: |
          terraform plan -input=false
      
      # On PR events, comment on the PR with the TF step statuses
      # The always() allows this step to run regardless of whether the steps above failed, as we want to see which stage failed
      - name: Update PR with Terraform quality step outputs
        uses: actions/github-script@v7.0.1
        if: github.event_name == 'pull_request' && always()
        with:
          github-token: ${{ secrets.INTEGRATION_TOKEN }}
          script: |
            const output = `## Terraform Quality Check Update 🤖
            This is an automated message generated by the CI run. It displays the statuses of the formatting, initialisation, validation and planning of the Terraform source files.
            
            ## Quality Check 
            <details>
            <summary><h4>🖌 Terraform Format and Style</h4></summary>
            \'${{ steps.fmt.outcome }}\'
            </details>

            <details>
            <summary><h4>⚙️ Terraform Initialization</h4></summary>
            \'${{ steps.init.outcome }}\'
            </details>

            <details>
            <summary><h4>✅ Terraform Validation</h4></summary>
            \'${{ steps.validate.outcome }}\'
            </details>

            ## Plan 
            <details>
            <summary><h4>Plan Output</h4></summary>
            ```
            ${{ steps.planStep.outputs.stdout }}
            ```
            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })